source("src/metadata.R")

sample60.old <- taxonomyReportDBConnect("data/taxonomyDB/sample60_bac.db", metadata60)
sample60.new <- taxonomyReportDBConnect("data/taxonomyDB/sample60.new.bac.db", metadata60)
sample62.old <- taxonomyReportDBConnect("data/taxonomyDB/sample62_bac.db", metadata62) 
#sample62.new <- taxonomyReportDBConnect("data/taxonomyDB/sample62.new.bac.db", metadata62)
sample64.new <- taxonomyReportDBConnect("data/taxonomyDB/sample64.new.bac.db", metadata64) 
sample66.old <- taxonomyReportDBConnect("data/taxonomyDB/sample66_bac.db", metadata66)
#sample66.new <- taxonomyReportDBConnect("data/taxonomyDB/sample66.new.bac.db", metadata66) 
sample68.old <- taxonomyReportDBConnect("data/taxonomyDB/sample68_bac.db", metadata68) 
#sample66.new <- taxonomyReportDBConnect("data/taxonomyDB/sample68.new.bac.db", metadata68) 
sample70.old <- taxonomyReportDBConnect("data/taxonomyDB/sample70_bac.db", metadata70) 
#sample70.new <- taxonomyReportDBConnect("data/taxonomyDB/sample70.new.bac.db", metadata70) 
#sample72.new <- taxonomyReportDBConnect("data/taxonomyDB/sample72.new.bac.db", metadata72) 
sample74.new <- taxonomyReportDBConnect("data/taxonomyDB/sample74.new.bac.db", metadata74) 
sample76.old <- taxonomyReportDBConnect("data/taxonomyDB/sample76_bac.db", metadata76) 
#sample76.new <- taxonomyReportDBConnect("data/taxonomyDB/sample76.new.bac.db", metadata76) 
sample78.old <- taxonomyReportDBConnect("data/taxonomyDB/sample78_bac.db", metadata78) 
#sample78.new <- taxonomyReportDBConnect("data/taxonomyDB/sample78.new.bac.db", metadata78) 
sample80.old <- taxonomyReportDBConnect("data/taxonomyDB/sample80_bac.db", metadata80) 
#sample80.new <- taxonomyReportDBConnect("data/taxonomyDB/sample80.new.bac.db", metadata80) 
sample82.old <- taxonomyReportDBConnect("data/taxonomyDB/sample82_bac.db", metadata82) 
#sample82.new <- taxonomyReportDBConnect("data/taxonomyDB/sample82.new.bac.db", metadata82) 